[platformio]
core_dir = .pio-core

[env:cores3]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = arduino
platform_packages =
    platformio/framework-arduinoespressif32@3.20017.0
    espressif/toolchain-xtensa-esp32s3@8.4.0+2021r2-patch5
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.embed_txtfiles = certs/gts-root-r4.pem
board_build.embed_files =
    assets/generated/sara.rgb
    assets/generated/startup.pcm
    config/character.json
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    m5stack/M5Unified@0.2.11
    m5stack/M5GFX@0.2.28
    links2004/WebSockets@2.6.1
    bblanchon/ArduinoJson@7.4.2
